# Generated by Django 6.0.1 on 2026-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        default="Индивидуальный предприниматель",
                        max_length=100,
                        verbose_name="Организационно-правовая форма",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Например: Фамилия Имя Отчество",
                        max_length=255,
                        verbose_name="ФИО предпринимателя",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Например: ИП Фамилия И.О.",
                        max_length=100,
                        verbose_name="Сокращённое наименование",
                    ),
                ),
                ("ogrnip", models.CharField(max_length=15, verbose_name="ОГРНИП")),
                ("inn", models.CharField(max_length=12, verbose_name="ИНН")),
                (
                    "legal_address",
                    models.TextField(
                        help_text="Полный адрес с индексом",
                        verbose_name="Юридический адрес",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=6, verbose_name="Индекс"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        help_text="В формате +7 (999) 999-99-99",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="Пн–Пт 09:00–18:00 (МСК)",
                        max_length=100,
                        verbose_name="Режим работы",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование банка"
                    ),
                ),
                ("bik", models.CharField(blank=True, max_length=9, verbose_name="БИК")),
                (
                    "checking_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Расчётный счёт"
                    ),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Корреспондентский счёт"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="PKUBG",
                        max_length=100,
                        verbose_name="Название магазина",
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        default="https://pkubg.ru", verbose_name="URL сайта"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        default="Интернет-магазин низкобелковой и безглютеновой продукции",
                        verbose_name="Описание магазина",
                    ),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                ("ozon_url", models.URLField(blank=True, verbose_name="Ozon")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Юридическая информация",
                "verbose_name_plural": "Юридическая информация",
            },
        ),
    ]
