# Generated by Django 4.2.7 on 2025-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_carts', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
