# Generated by Django 6.0.1 on 2026-01-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Комментарий к заказу"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(default="courier", max_length=50),
        ),
    ]
