# Generated by Django 4.2.7 on 2025-12-18 13:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.JSONField(default=products.models.get_default_nutritional_info),
        ),
    ]
