# Generated by Django 4.2.7 on 2025-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, verbose_name='Условия хранения'),
        ),
    ]
