# Generated by Django 6.0.1 on 2026-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_composition_product_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_egg_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_lactose_free",
            field=models.BooleanField(default=False),
        ),
    ]
