# Generated by Django 6.0.1 on 2026-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_is_egg_free_product_is_lactose_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reserved_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
